stable_version: 2.7.3
stable_release_url: http://ironpython.codeplex.com/releases/view/81726
stable_release_date: 2.7.3 released on 2012-07-06
stable_release_notes: http://ironpython.codeplex.com/releases/view/81726
stable_release_source: https://github.com/IronLanguages/main/zipball/ipy-2.7.3
