stable_version: 2.7.6.3
stable_release_url: https://github.com/IronLanguages/main/releases/tag/ipy-2.7.6.3
stable_release_date: 2.7.6.3 released on 2016-08-20
stable_release_notes: https://github.com/IronLanguages/main/releases/tag/ipy-2.7.6.3
stable_release_source: https://github.com/IronLanguages/main/zipball/ipy-2.7.6.3

paginate: 10
paginate_path: "/blog/page:num/"
