stable_version: 2.7.4
stable_release_url: http://ironpython.codeplex.com/releases/view/90087
stable_release_date: 2.7.4 released on 2013-09-07
stable_release_notes: http://ironpython.codeplex.com/releases/view/90087
stable_release_source: https://github.com/IronLanguages/main/zipball/ipy-2.7.4
